#!/bin/sh
cat << __EOC__
$ ./configure  '--with-readline=/usr/include/readline' '--disable-conio' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--with-scriptdir=/etc/bacula/scripts' '--with-working-dir=/var/lib/bacula' '--with-logdir=/var/log' '--enable-smartalloc' '--with-postgresql' '--with-archivedir=/home/backup' '--with-job-email=suporte@seudominio.com.br' '--with-hostname=127.0.0.1'

Configuration on Sat Aug 15 01:06:36 UTC 2020:

   Host:                      x86_64-pc-linux-gnu -- ubuntu 18.04
   Bacula version:            Bacula 9.6.5 (11 June 2020)
   Source code location:      .
   Install binaries:          /usr/sbin
   Install libraries:         /usr/lib64
   Install config files:      /etc/bacula
   Scripts directory:         /etc/bacula/scripts
   Archive directory:         /home/backup
   Working directory:         /var/lib/bacula
   PID directory:             /var/run
   Subsys directory:          /var/lock/subsys
   Man directory:             /usr/share/man
   Data directory:            /usr/share
   Plugin directory:          /usr/lib64
   C Compiler:                gcc 7.5.0-3ubuntu1~18.04)
   C++ Compiler:              /usr/bin/g++ 7.5.0-3ubuntu1~18.04)
   Compiler flags:             -g -O2 -Wall -x c++ -fno-strict-aliasing -fno-exceptions -fno-rtti
   Linker flags:               
   Libraries:                 -lpthread -ldl -ldl 
   Statically Linked Tools:   no
   Statically Linked FD:      no
   Statically Linked SD:      no
   Statically Linked DIR:     no
   Statically Linked CONS:    no
   Database backends:         PostgreSQL
   Database port:              
   Database name:             bacula
   Database user:             bacula
   Database SSL options:      

   Job Output Email:          suporte@seudominio.com.br
   Traceback Email:           root@localhost
   SMTP Host Address:         localhost

   Director Port:             9101
   File daemon Port:          9102
   Storage daemon Port:       9103

   Director User:             
   Director Group:            
   Storage Daemon User:       
   Storage DaemonGroup:       
   File Daemon User:          
   File Daemon Group:         

   Large file support:        yes
   Bacula conio support:      no -lreadline -lhistory 
   readline support:          yes 
   TCP Wrappers support:      no 
   TLS support:               yes
   Encryption support:        yes
   ZLIB support:              yes
   LZO support:               yes
   S3 support:                no
   enable-smartalloc:         yes
   enable-lockmgr:            no
   bat support:               no
   client-only:               no
   build-dird:                yes
   build-stored:              yes
   Plugin support:            yes
   AFS support:               no
   ACL support:               yes
   XATTR support:             yes
   systemd support:           no 
   Batch insert enabled:      PostgreSQL

   Plugins:
   - Docker:                  no
  
__EOC__
