version: '3.1'
#
services:
#    
  db:
    build: bacula-catalog/
    image: fametec/bacula-catalog:9.6.5
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: bacula
      POSTGRES_USER: bacula
      POSTGRES_DB: bacula
    # volumes:
    #   - pgdata:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
#
  bacula-standalone:
    build: bacula-standalone/
    image: fametec/bacula-standalone:9.6.5
    restart: unless-stopped
    volumes:
      - ./etc-standalone:/opt/bacula/etc:rw
      - ./etc-standalone/baculum:/etc/baculum:rw
    depends_on: 
      - db      
    ports:
      - 9101:9101
      - 9102:9102
      - 9103:9103
      - 9095:9095
      - 9096:9096
# 
#volumes: 
#  pgdata:
