version: '3.1'
#
services:

  base: 
    build: bacula-base/
    image: fametec/bacula-base:9.6.5
#    
  db:
    build: bacula-catalog/
    image: fametec/bacula-catalog:9.6.5
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: WR$$segur@
      POSTGRES_USER: bacula
      POSTGRES_DB: bacula
    # volumes:
    #   - pgdata:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
#
  bacula-dir:
    build: bacula-dir/
    image: fametec/bacula-director:9.6.5
    restart: unless-stopped
    volumes:
      - ./etc:/opt/bacula/etc:ro
    depends_on: 
      - db      
    ports:
      - 9101:9101
#
  bacula-sd:
    build: bacula-sd/
    image: fametec/bacula-storage:9.6.5
    restart: unless-stopped
    depends_on:
      - bacula-dir
      - db
    volumes:
      - ./etc:/opt/bacula/etc:ro
    ports:
      - 9103:9103
#
  bacula-fd:
    build: bacula-fd/
    image: fametec/bacula-client:9.6.5
    restart: unless-stopped
    depends_on:
      - bacula-sd
      - bacula-dir
      - db
    volumes:
      - ./etc:/opt/bacula/etc:ro
    ports:
      - 9102:9102
#
  baculum:
    build: baculum/
    image: fametec/baculum:9.6.5
    restart: unless-stopped
    depends_on: 
      - db
      - bacula-dir
    volumes:
      - ./etc/bconsole.conf:/opt/bacula/etc/bconsole.conf:ro
      - ./etc/baculum:/etc/baculum:rw
    ports:
      - 9095:9095
      - 9096:9096
# 
#volumes: 
#  pgdata:
